# Simple workflow for deploying static content to GitHub Pages
name: Deploy Documentation to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir uv
      - name: Setup uv
        run: |
          uv python pin 3.14
          uv add --group docs sphinx pydata-sphinx-theme myst-parser sphinx-copybutton
          uv lock --upgrade-package sphinx
          uv lock --upgrade-package pydata-sphinx-theme
          uv lock --upgrade-package myst-parser
          uv lock --upgrade-package sphinx-copybutton
          uv sync --group docs
      - name: Build with Sphinx
        run: |
          uv run sphinx-apidoc -f -o docs src/python_pkg_template
          uv run sphinx-build -b html docs html
      - name: Add .nojekyll
        run: echo "" > html/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
